### ISSUE TITLE
Adding requests doesn't seem to be asynchronous

### ISSUE THREAD

**Issue by notr1ch** [evdb/HTTP-Async#13]
Not sure if this is by design or a bug, but when I'm adding HTTP::Requests to https sites it seems there is a small blocking delay after adding each request. With 30 requests, it takes ~ 4 seconds to add them to the HTTP::Async object before I can begin polling for responses.

I initially thought maybe a blocking DNS lookup was to blame but the hostnames are all in the localhost DNS cache so it should be very fast. Any ideas?

**Comment by notr1ch** [comment]
Sorry, just saw the TODO and this is currently known behavior.

**Comment by kaoru** [comment]
No worries @notr1ch :) Thanks for using HTTP::Async!

**Comment by dorszman** [comment]
I've a fix for this.
Please find in pull requests: SSL: async connection
